version: 0.0
os: linux
files:
  - source: dist/MyAngular-Project1
    destination: /var/www/MyAngular-Project1
permissions:
  - object: /var/www/MyAngular-Project1
    pattern: '**'
    mode: '0755'
    owner: root
    group: root
    type:
      - file
      - directory
hooks:
  ApplicationStart:
    - location: deploy-scripts/application-start-hook.sh
      timeout: 300
      